### ISSUE TITLE
Feature request: V3 alpha branch with removal of obsolete APIs

### ISSUE THREAD

**Issue by bartelink** [Azure/azure-documentdb-changefeedprocessor-dotnet#129]
I find the codebase very difficult to traverse due to the residual duplicate code from the obsoleted V1 API (for evidence see #84 and #123). It doesn't seem to be a straight case of removing the Obsolete folder and seeing one clear set of DRY unambiguous code. I suspect this will harm adoption of this library for no good reason.

The first step on this journey would be a prominent deprecation warning in the readme.md, which I think should happen sooner, rather than later

(If I'm missing something and it is simply a matter of deleting a folder and a file or two, I'm happy, but from a 15 minute attempt, it seems many classes have mixes between code needed for V2 and stuff only needed for V1)

**Comment by ealsur** [comment]
Just cleaning things. This issue is closed based on the work being done in SDK V3 https://github.com/Azure/azure-cosmos-dotnet-v3/pulls
