### ISSUE TITLE
Support .Net Framework 4.6 or above

### ISSUE THREAD

**Issue by maoz123** [Azure/azure-documentdb-changefeedprocessor-dotnet#130]
Currently, we can use change feed .net framework 4.5.1. Our project need to upgrade to 4.6.2 to improve stability. I know that nuget package of ChangeFeedProcessor currently only support v.4.5. when will you release a package that works in .net framework 4.6 or above? Waiting for your confirm. Or could we build a ChangeFeedProcessor nuget on .net framework 4.6.2 and upload the nuget to our own nuget server to match our requirements?

**Comment by bartelink** [comment]
In general, `net46x` can use a `net45` nuget with no dramas (at work, for OSS releases, we tend to use `net461` as a minimum bar as that hits a lot of hosting scenarios)
If you can get to `net472` your side, then the [`netstandard2.0` support already in the package](https://www.fuget.org/packages/Microsoft.Azure.DocumentDB.ChangeFeedProcessor/2.2.5) would surely suffice though ?

**Comment by ealsur** [comment]
According to [NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support), 4.6.1 is `netstandard 2.0` compliant. So 4.6.2 should also be covered with the NET Standard 2.0 support.

**Comment by ealsur** [comment]
@maoz123 I'm closing this issue as this support already exists. Please reopen if you run into any issues using the latest nuget version with net46.
