### ISSUE TITLE
ChangeFeedProcessor sees only one partition

### ISSUE THREAD

**Issue by hellhax** [Azure/azure-documentdb-changefeedprocessor-dotnet#140]
1) I have a partitioned container (partition key = /type). I have four partitions (as presented on screen below). 
![image](https://user-images.githubusercontent.com/2691622/57708730-1f954d00-766a-11e9-96a2-7aa3564b9786.png)

2) I am running sample from [here](https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet#example) 
3) When I start the example it only sees one partition (0). No matter which document I modify (from which partition A, B, C or D) it says the change was on partition 0. 
![image](https://user-images.githubusercontent.com/2691622/57708897-64b97f00-766a-11e9-87d2-f7c208be50af.png)

4) If I run multiple instances of the example, I'd assume updates will be load balanced. This is not the case. Each instance gets the same change and each instance says the change happened on partition 0. Also lease partition contains only one document.
![image](https://user-images.githubusercontent.com/2691622/57709241-f75a1e00-766a-11e9-95b5-ff01428464bf.png)

5) If I run other reader with different **hostname**, it wont receive updates. However if I change lease collection for that new reader to some new one, it starts working as in 4). In that case each 
lease partition contains only one document. 

I don't think it is supposed to work that way. I am under impression that load balancing and leases are broken. But I might be missing sth.  Can anyone advise?

**Comment by mkowalskigps** [comment]
I believe what you're seeing is intended behavior - the change feed processor operates at a physical partition level not a logical partition level, so although you do have 4 logical partitions, you only have a single physical partition. The easiest way to confirm this is to look at the metrics of your container in the portal: https://docs.microsoft.com/en-us/azure/cosmos-db/use-metrics

**Comment by hellhax** [comment]
Ok thanks. Now it makes sense :) 

I'd suggest putting that info (physical partition) into documentation though.
