### ISSUE TITLE
Parsing DateTimeOffset

### ISSUE THREAD

**Issue by ChiefWiggum** [Azure/azure-documentdb-changefeedprocessor-dotnet#141]
We're using DateTimeOffsets in CosmosDB, but when using the Change Feed Processor library (v2) the dates always get converted. This can be resolved by using a custom `DocumentClient` that has custom `JsonSerializerSettings` and then use this client with `.WithFeedDocumentClient(docClient)` when building it.

```
var serializerSettings = new JsonSerializerSettings
{
    DateParseHandling = DateParseHandling.DateTimeOffset
};

var docClient  = new DocumentClient(config.Database.Uri, config.Database.Write.Key, serializerSettings);

var builder = new ChangeFeedProcessorBuilder();

_processor = await builder
    .WithFeedDocumentClient(docClient)
    .BuildAsync();

await _processor.StartAsync();
```

Is this the recommended way of solving the parsing issue?

**Comment by ealsur** [comment]
This issue is really tied to the V2 SDK, this library does not have any particular logic or code that relies on the SDK behaving one way or the other.

The way you solved the scenario is basically what I would recommend.
