### ISSUE TITLE
Documentation issue: what kind of partition?

### ISSUE THREAD

**Issue by vhe1** [Azure/azure-documentdb-changefeedprocessor-dotnet#145]
The readme mentions partitions several times. However. it never makes clear whether the change feed processor leases physical or logical partitions.

(This is relevant in scenarios where multiple readers are used for performance reasons. For instance, if there are thousands of small logical partitions, all residing in the same physical partition, adding more change feed processing workers won't speed up things.)

So, would you please clarify that in the documentation?
(The city name ranges _seem_ to indicate physical partitions, but it'd be nice to be sure.)

**Comment by ealsur** [comment]
Currently, the lease = physical partition.
