### ISSUE TITLE
Cosmos DB 2.0.0 support

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-documentdb-changefeedprocessor-dotnet#96]
Cosmos DB SDK 2.0.0 changed method signatures, see https://github.com/Azure/azure-cosmosdb-dotnet/issues/578

We need to address it with a new minor version and reference updates.

**Comment by jbogard** [comment]
Ha I literally just hit this today with the preview build!

**Comment by ealsur** [comment]
@jbogard Are you referencing `2.0.0-preview` or `2.0.0-preview2`?

**Comment by jbogard** [comment]
preview2.

**Comment by kadukf** [comment]
yeah, I was discussing this with Micheal last month so that we could release "preview" withi SDk2.0 preview, wdyt?

**Comment by ealsur** [comment]
I bumped the version to a 2.1.0-preview in the PR

**Comment by kadukf** [comment]
#102
